src/rajawali/Object3D.java

While cloning Object3Ds created by LoaderOBJ I found that models often contained children which also need to be cloned to achieve the expected result.

Object3D cloning to include children

---

src/rajawali/math/Quaternion.java

Fixed a bug in the equals function that caused it to return always false
if dot(other) returned > 1.0
Thanks to @jwoolston for providing the fix.

Fixed a bug in the equals function

---

.idea/inspectionProfiles/Project_Default.xml
.idea/inspectionProfiles/profiles_settings.xml
rajawali/src/main/java/rajawali/postprocessing/APass.java
rajawali/src/main/java/rajawali/postprocessing/IPass.java
rajawali/src/main/java/rajawali/postprocessing/PostProcessingManager.java
rajawali/src/main/java/rajawali/postprocessing/passes/ClearMaskPass.java
rajawali/src/main/java/rajawali/postprocessing/passes/CopyToNewRenderTargetPass.java
rajawali/src/main/java/rajawali/postprocessing/passes/DepthPass.java
rajawali/src/main/java/rajawali/postprocessing/passes/EffectPass.java
rajawali/src/main/java/rajawali/postprocessing/passes/MaskPass.java
rajawali/src/main/java/rajawali/postprocessing/passes/RenderPass.java
rajawali/src/main/java/rajawali/postprocessing/passes/ShadowPass.java
rajawali/src/main/java/rajawali/renderer/AFrameTask.java
rajawali/src/main/java/rajawali/renderer/RajawaliRenderer.java
rajawali/src/main/java/rajawali/renderer/RajawaliSideBySideRenderer.java
rajawali/src/main/java/rajawali/scene/ASceneFrameCallback.java
rajawali/src/main/java/rajawali/scene/RajawaliScene.java

Allows user code to register for pre- frame and post-frame callbacks. These callbacks receive not only the frame delta time, but also the elapsed render time in nanoseconds, allowing for more complex physics and animations in an easy to plugin fashion. Implementations can register for pre only, post only or both callbacks.

Adds a new render frame callback system

---

src/rajawali/materials/textures/ASingleTexture.java

User is expected to provide bitmaps for all supported densities. For issue #1369

prevent bitmap auto scaling.

---

rajawali/src/main/java/rajawali/Camera.java
rajawali/src/main/java/rajawali/Geometry3D.java
rajawali/src/main/java/rajawali/Object3D.java
rajawali/src/main/java/rajawali/animation/mesh/SkeletalAnimationObject3D.java
rajawali/src/main/java/rajawali/bounds/BoundingBox.java
rajawali/src/main/java/rajawali/bounds/BoundingSphere.java
rajawali/src/main/java/rajawali/parser/Loader3DSMax.java
rajawali/src/main/java/rajawali/parser/LoaderMD2.java
rajawali/src/main/java/rajawali/parser/LoaderOBJ.java
rajawali/src/main/java/rajawali/parser/LoaderSTL.java
rajawali/src/main/java/rajawali/parser/awd/BlockTriangleGeometry.java
rajawali/src/main/java/rajawali/parser/fbx/LoaderFBX.java
rajawali/src/main/java/rajawali/parser/md5/LoaderMD5Mesh.java
rajawali/src/main/java/rajawali/postprocessing/passes/CopyToNewRenderTargetPass.java
rajawali/src/main/java/rajawali/postprocessing/passes/DepthPass.java
rajawali/src/main/java/rajawali/postprocessing/passes/EffectPass.java
rajawali/src/main/java/rajawali/primitives/Cube.java
rajawali/src/main/java/rajawali/primitives/Line3D.java
rajawali/src/main/java/rajawali/primitives/NPrism.java
rajawali/src/main/java/rajawali/primitives/Plane.java
rajawali/src/main/java/rajawali/primitives/PointSprite.java
rajawali/src/main/java/rajawali/primitives/RectangularPrism.java
rajawali/src/main/java/rajawali/primitives/ScreenQuad.java
rajawali/src/main/java/rajawali/primitives/Sphere.java
rajawali/src/main/java/rajawali/renderer/RajawaliRenderer.java
rajawali/src/main/java/rajawali/renderer/plugins/IRendererPlugin.java
rajawali/src/main/java/rajawali/renderer/plugins/LensFlarePlugin.java
rajawali/src/main/java/rajawali/renderer/plugins/Plugin.java
rajawali/src/main/java/rajawali/scene/RajawaliScene.java
rajawali/src/main/java/rajawali/terrain/TerrainGenerator.java

Allows objects to be constructed before an EGL context is available. This is useful if the `RajawaliFragment` is in a view pager, or if you need it in an app that will have multiple screens. This is the first step in allowing for completely creating a scene prior to `initScene()`, and thus asynchronously creating scenes.

Allows for lazy VBO creation

---

rajawali/src/main/java/rajawali/Object3D.java
rajawali/src/main/java/rajawali/materials/Material.java
rajawali/src/main/java/rajawali/renderer/RajawaliRenderer.java

Adds an option to materials for deferred checking of device capabilities (used for determining maximum texture count). If it is deferred and you add too many textures, an error message will be printed but the maximum possible number of textures will be used, going in list order. Along with this, an option has been added to allow a RajawaliRenderer implementation to register with the resource managers in its constructor rather than waiting until onSurfaceCreated(). If you register in the constructor, registration will not occur in the onSurfaceCreated callback.

Adds an option to materials for deferred checking of device capabilities

---

rajawali/src/main/java/rajawali/Capabilities.java
rajawali/src/main/java/rajawali/RajawaliActivity.java
rajawali/src/main/java/rajawali/RajawaliDaydream.java
rajawali/src/main/java/rajawali/RajawaliFragment.java
rajawali/src/main/java/rajawali/RajawaliSupportFragment.java
rajawali/src/main/java/rajawali/materials/textures/ACompressedTexture.java
rajawali/src/main/java/rajawali/materials/textures/Etc2Texture.java
rajawali/src/main/java/rajawali/materials/textures/utils/ETC2Util.java
rajawali/src/main/java/rajawali/util/egl/RajawaliEGLConfigChooser.java

Adds ETC2 texture support for GLES 3.0 and better devices. The new class `Etc2Texture` can accomadate both ETC1 and ETC2 textures. Additionally, all rendering surfaces will now automatically select GLES 3.0 if the device supports it, 2.0 otherwise.

Adds ETC2 texture support

---

rajawali/src/main/java/org/rajawali3d/ATransformable3D.java
rajawali/src/main/java/org/rajawali3d/Camera.java
rajawali/src/main/java/org/rajawali3d/WorldParameters.java
rajawali/src/main/java/org/rajawali3d/lights/DirectionalLight.java
rajawali/src/main/java/org/rajawali3d/lights/SpotLight.java
rajawali/src/main/java/org/rajawali3d/loader/fbx/LoaderFBX.java
rajawali/src/main/java/org/rajawali3d/math/Quaternion.java
rajawali/src/main/java/org/rajawali3d/math/vector/Vector3.java

Part of Issue #1376 required fixes to the Quaternion class. Most notably, the degenerate case of the look vector being parallel/anti-parallel to the up vector was not being handled. Additionally, in ATransformable3D the look vector was being miscalculated, preventing the detection of the look vector being anti-parallel to the up vector.

Numerous Quaternion related fixes

---

rajawali/src/main/java/org/rajawali3d/loader/LoaderAWD.java
rajawali/src/main/java/org/rajawali3d/loader/awd/BlockMeshInstance.java
rajawali/src/main/java/org/rajawali3d/loader/awd/BlockSimpleMaterial.java

Loads all material attributes from AWD file. The assignment of materials to child objects (where present) follows the implementation in the AwayBuilder source: assign sequentially and repeat the last material in the case where there are additional objects. Also adds a missing break in LoaderAWD switch.

Load all AWD material attributes; specularity/specular map, normal map, diffuse and ambient textures/levels/colors, etc

---

rajawali/src/main/java/org/rajawali3d/materials/AResourceManager.java

Right now renderers are being registered twice in both TextureManager and MaterialManager: on render constructor and in onSurfaceCreated. They are also re-added on subsequent calls to onSurfaceCreated.

Fixes leaks with managers (#1336)

---

rajawali/src/main/java/org/rajawali3d/materials/textures/AnimatedGIFTexture.java

Clears before drawing the canvas to support transparent GIFs.

Fix for Issue #1355 -- Animated GIF & Alpha Channel.

---

rajawali/src/main/java/org/rajawali3d/surface/RajawaliSurfaceView.java
rajawali/src/main/java/org/rajawali3d/surface/RajawaliTextureView.java

RajawaliSurface currently uses the attribute counter as the input to TypedArray.getXYZ when parsing the custom surfaceview style, whereas it should be using the RajawaliSurface_[attribute] values.

Bugfix: TypedArray.get for custom styles takes attribute index, not array index

---

rajawali/src/main/java/org/rajawali3d/ATransformable3D.java
rajawali/src/main/java/org/rajawali3d/math/vector/Vector3.java

Vector3.normalize's contract stipulates that it will return the original magnitude of the vector; currently it returns the reciprocal of the magnitude. Similarly, the setRotation methods in ATransformable should set the absolute value of mOrientation from the supplied arguments, but currently apply the rotation to the existing orientation and are therefore indistinguishable from the rotate() methods.

Fixes semantic issues with a couple of methods.

---

rajawali/src/main/java/org/rajawali3d/surface/RajawaliSurfaceView.java

RajawaliSurfaceView was initialized with 0 bits for mBitsAlpha and there was no way to alter that value programatically. Not every combination of RGB and A sizes works. So, I force 8888 when mIsTransparent.

Pick a suitable config (8888) when background is transparent

---

rajawali/src/main/java/org/rajawali3d/materials/Material.java

This is a very minor PR, just trying to point out what I think is a small mistake?
Note that I am very very far from an expert but my common sense reading this code makes me feel the texture attachment GL calls are done twice. (once in the code block I removed and then again in the ```bindTextureByName``` method above)
If that duplication was intentional please disregard this PR.

Remove redundant code?

---

rajawali/src/main/java/org/rajawali3d/util/Capabilities.java

See commit message...
If the secondary check (for color bit sizes) is not useful as-is, I'll be happy to remove/modify it and retest.
I ran all the examples on my S3 and noted anything unusual in the attached file:
[issue-1504 example notes.txt](https://github.com/Rajawali/Rajawali/files/163926/issue-1504.example.notes.txt)
Of particular interest: ETC2 provides an appropriate message that ES 3 is not supported, and a Vuforia crash.
As an aside, libVuforia.so is getting (re)built every time even though it is under source control, and so shows up as modified. Is this intentional?
Let me know if there are any git/branching issues I've missed.

PR for #1504

---

rajawali/src/main/java/org/rajawali3d/scene/Scene.java

- wrong counter ("preCount" instead of "preRenderCount") used in preDraw for loop in render()
- renamed counter to match callback ("preDrawCount") to minimize future confusion
NOTE: Haven't tested this...

PR to fix preDraw count bug (no issue #)

---

examples/src/main/java/org/rajawali3d/examples/examples/interactive/TouchAndDragFragment.java
rajawali/src/main/java/org/rajawali3d/Object3D.java
rajawali/src/main/java/org/rajawali3d/scene/Scene.java
rajawali/src/main/java/org/rajawali3d/util/ObjectColorPicker.java

Fixes #1607 
* Scene.java
* added `doColorPicking()` to isolate color-picking render from normal render() control flow
* renamed `requestColorPickingTexture()` to `requestColorPicking()` 
* Object3D.java
* introduced `UNPICKABLE` color/index, made it a default value
* updated `setPickingColor()`, removed `getPickingColor()`
* eliminated `mIsPickingEnabled`, now check for `UNPICKABLE`
* added `renderColorPicking()` for optimized/independent color-picking rendering of the `Object3D` and its children (per #1387)
* ObjectColorPicker.java
* updated `unregisterObject()` to reset picking color to UNPICKABLE
* renamed `createColorPickingTexture()` to `pickObject()`
* in `pickObject()` call to `GLES20.glReadPixels()`, replaced `getDefaultViewportHieght()` with `getViewportHeight()`
* Examples: …

PR for #1607 - combining object color picking and post-processing

---

examples/src/main/java/org/rajawali3d/examples/examples/postprocessing/RenderToTextureFragment.java
rajawali/src/main/java/org/rajawali3d/materials/AResourceManager.java
rajawali/src/main/java/org/rajawali3d/materials/textures/RenderTargetTexture.java
rajawali/src/main/java/org/rajawali3d/materials/textures/TextureManager.java
rajawali/src/main/java/org/rajawali3d/postprocessing/PostProcessingManager.java
rajawali/src/main/java/org/rajawali3d/renderer/RenderTarget.java
rajawali/src/main/java/org/rajawali3d/renderer/Renderer.java

Fixes #1611. Adds a task call for resizing render target textures and updates the post processing manager to handle the size differences automatically.

Fixes #1611

---

examples/src/main/java/org/rajawali3d/examples/examples/interactive/ObjectPickingFragment.java
rajawali/src/main/java/org/rajawali3d/Object3D.java

This is embarrassing. I apparently muffed the testing for picking nested child objects (probably dropped the ball in properly updating my app - which uses nested children - with the new Rajawali library for the original branch).
- Object3D: correcting recursive call in renderColorPicking()!
- Enhancing ObjectPicking example with a couple of simple containers to better detect regressions of child picking...

Fix for color-picking of nested child objects (see #1607)

---

rajawali/src/main/java/org/rajawali3d/Object3D.java
rajawali/src/main/java/org/rajawali3d/scene/Scene.java
rajawali/src/main/java/org/rajawali3d/util/ObjectColorPicker.java

* Scene.java:
* moving glClearDepth() prior to glClear()!
* Object3D.java:
* eliminating unused parameters from renderColorPicking() signature
* Comment clean-ups
* ObjectColorPicker.java:
* Improving thread safety of mObjectLookup list
* Filtering out requests when there is no listener
* Skipping picking if there is no listener, and avoiding conflicts with setOnObjectPickedListener()...
* Guarding against holes in the index due to unregistered objects and so returning null in onObjectPicked()

Misc fixes/improvements to color-picking (due to investigating #1615)

---

rajawali/src/main/java/org/rajawali3d/primitives/ScreenQuad.java
rajawali/src/main/java/org/rajawali3d/scene/Scene.java

Per the GL ES 2.0 spec: "The pixel ownership test, the scissor test, dithering, and the _buffer writemasks_ affect the operation of glClear."
Prior optimization attempt was inccorrect; just making the depth testing config in Scene.doColorPicking() identical to Scene.render()...
Also, duplicating fix for ScreenQuad orientation.

Fixing #1615

---

vuforia/build.gradle

Implemented the second part of of issue 1663, added an error message if NDK is not found.
Do not know the vuforia build components well enough to risk messing with that.

added an unknown NDK location error message.

---

build.gradle
rajawali/src/main/java/org/rajawali3d/scene/Scene.java

Sorry, forgot to branch each change, so two issues got mixed in one pull request.
- removed the `alpha3` build tool specifier, see issue #1693 
- defers camera frustum far panel adjustment in `setSkyBox`, see issue #1695

broadened dependencies to also include stable build tools

---

examples/src/main/java/org/rajawali3d/examples/data/DataSet.java
examples/src/main/java/org/rajawali3d/examples/examples/animation/SkeletalAnimationBlendingFragment.java
examples/src/main/java/org/rajawali3d/examples/examples/postprocessing/FXAAFragment.java
examples/src/main/res/layout/fxaa_button_bar.xml
examples/src/main/res/layout/skeletal_blending_creator_bar.xml
examples/src/main/res/values/strings.xml
rajawali/src/main/java/org/rajawali3d/postprocessing/passes/EffectPass.java
rajawali/src/main/java/org/rajawali3d/postprocessing/passes/FXAAPass.java
rajawali/src/main/java/org/rajawali3d/util/Capabilities.java
rajawali/src/main/java/org/rajawali3d/util/RajLog.java
rajawali/src/main/res/raw/fxaa_fragment_shader.glsl
rajawali/src/main/res/raw/fxaa_vertex_shader.glsl

Inspired by #1721 
Adds Fast Approximate Anti-Aliasing (FXAA) post processing pass and example compatible with all API levels. This is a basic initial implementation. I have plans on working on adding "tuning" options to the shader as well as some efficiency changes. The included example shows a good best and worst case scenario with respect to FXAAs shortcomings to vertical/horizontal edges and strengths with long diagonal edges. 
FXAA Off
FXAA On

Working version of FXAA pass.

---

examples/src/main/java/org/rajawali3d/examples/examples/scene/ObjectAddRemoveFragment.java
rajawali/src/main/java/org/rajawali3d/Geometry3D.java
rajawali/src/main/java/org/rajawali3d/Object3D.java

Following the logic of #1610, this removes the automatic material removal when calling Object3D#destroy(). Additionally, prevents Geometry3D#destroy() from destroying any parent geometry which may still be in use by other objects.

Fixes #1718 

---

rajawali/src/main/java/org/rajawali3d/Geometry3D.java

Proposed Fix for #1760 
Augmented getFloatArrayFromBuffer() and getIntArrayFromBuffer() to return null when the input buffer is null.
Augmented addFromGeometry3D() to test for null array values.

Fix for unexpected behaviour from Geometry3D.addFromGeometry3D

---

rajawali/src/main/java/org/rajawali3d/Geometry3D.java

Fix for #1766 
`setVertices()` already had a boolean override, this change adds a similar ability to
- `setNormals()`
- `setTextureCoords()`
- `setColors()`
- `setIndices()`
and their associated buffers

fix for unexpected behaviour when repeatedly calling Geometry3D.addFromGeometry3D()

---

rajawali/src/main/java/org/rajawali3d/util/ObjectColorPicker.java

When calling unregisterObject  the index doesn't change but now the size of the object lookup array is smaller and it might happen that some objects are no longer clickable or return the wrong one so instead of removing the item from the array we can just set the value to null.

Do not remove item from array to maintain the consistency with the index

---

rajawali/src/main/java/org/rajawali3d/renderer/Renderer.java

For the loading new models asynchronously the id of the new thread is just the size of the SparseArray at the moment, the id is then used to retrieve the the thread at the end of the execution but if other threads finished before they might influence the array leading to a NullPointerException when trying to retrieve the thread.
A more simple solution could be to have the last ID as a member but I wouldn't want to run into max int complications if there are A LOT of models loaded constantly and it shouldn't affect performance.

Get the first empty in the loader threads SparseArray and use it as ID for the new thread.

---

rajawali/src/main/java/org/rajawali3d/Geometry3D.java
rajawali/src/main/java/org/rajawali3d/Object3D.java
rajawali/src/main/java/org/rajawali3d/bounds/BoundingBox.java

Fix for issue #1774 
Opened pull request to get some guidance. For now only refactored code that search for min max points in Object3D's vertices.

Enable parent objects with no vertices to create Bounding Box

---

rajawali/src/main/java/org/rajawali3d/ATransformable3D.java
rajawali/src/main/java/org/rajawali3d/Object3D.java
rajawali/src/main/java/org/rajawali3d/materials/Material.java
rajawali/src/main/java/org/rajawali3d/math/Matrix4.java

- adding throws IllegalStateException to Matrix4.setToNormal() as it depends on Matrix4.inverse()
- putting call to setToNormal() in Material.setModelMatrix() in try/catch block, thus enabling continued rendering of degenerate/zero-scale Object3Ds (which have singular model matrices)
Tested on existing app where issue surfaced, no changes required.

Addressing issue #1784:

---

rajawali/src/main/res/raw/vignette_fragment_shader.glsl

Inner and Outer radii are now correctly derived from uRadius and uSmoothness.
Turns out that when vignette pass worked, it was due to undefined behaviour of smoothstep.
(smoothstep results are undefined if edge0 ≥ edge1)

Fix for issue #1796 unexpected behaviour from Vignette Pass

---

rajawali/src/main/java/org/rajawali3d/materials/textures/TextureManager.java

I am using this library and I am facing the following issue:
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:117)
at java.util.Collections$SynchronizedList.get(Collections.java:537)
at org.rajawali3d.materials.textures.TextureManager.taskReload(TextureManager.java:205)
at org.rajawali3d.renderer.Renderer.initScene(Renderer.java:366)
at com.sandro.aerial.RendererActivity.onRenderSurfaceSizeChanged(RendererActivity.java:206)
at org.rajawali3d.view.SurfaceView$RendererDelegate.onSurfaceChanged(SurfaceView.java:232)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1550)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1278)
```
I believe that with …

Fix Array index out of bounds exception in TextureManager

---

rajawali/src/main/java/org/rajawali3d/materials/MaterialManager.java

I am using this library and I am facing the following issue:
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:117)
at java.util.Collections$SynchronizedList.get(Collections.java:537)
at org.rajawali3d.materials.MaterialManager.taskReload(MaterialManager.java:71)
at org.rajawali3d.renderer.Renderer.initScene(Renderer.java:367)
at com.sandro.aerial.RendererActivity.onRenderSurfaceSizeChanged(RendererActivity.java:206)
at org.rajawali3d.view.SurfaceView$RendererDelegate.onSurfaceChanged(SurfaceView.java:232)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```
I believe that this PR can fix …

Fix out of bounds exception in material manager

---

rajawali/src/main/java/org/rajawali3d/primitives/ScreenQuad.java

fixes Tilted camera images on the ScreenQuad #1850

UV orientation in ScreenQuad primitive now matches that of Plane.

---

rajawali/src/main/java/org/rajawali3d/Object3D.java
rajawali/src/main/java/org/rajawali3d/scene/Scene.java

Ref: #1634 
This change allows color picking to work when there is a ScreenQuad involved in the scene, by properly rendering said quad in the background, like it happens with the generated scene.
In order to test this, please use branch `color-picker` in [my fork of the Tango Java samples](https://github.com/adamantivm/tango-examples-java/tree/color-picker). This branch includes modification to its `build.gradle` so that it will use a latest Rajawali 1.1 snapshot, so that it is possible to build the Rajawali fix and test it against this sample.
Please clone my fork, build the app `java_augmented_reality_example` and run it on a Tango-enabled device. You should see a rotating earth with a revolving moon against the backdrop of the live camera image. If you click on the earth, you should …

Move depth test for color picking to per-object

---

rajawali/src/main/java/org/rajawali3d/materials/shaders/AShaderBase.java

This addresses the issue raised in #1858
None too pleased with the `xyzw` nomenclature, but it seems the way forward, as `RVect4` inherits from `RVect3`

added xyzw() and rgba() functions to RVect4, and fixed w() assignment.

---

rajawali/src/main/java/org/rajawali3d/cameras/ArcballCamera.java

responding to #1868 
added `ScreenMappingRatio` setter and getter to `ArcballCamera`, value is 1,
setting this ratio to -1 accomodates the use case of looking at all sides small object
from the outside, without having an environment to give context to the camera movement.
Values from -1 to 1 are accepted, setting to 0 locks the `ArcballCamera` at the current orientation.

added ScreenMappingRatio setter and getter to ArcballCamera

---

rajawali/src/main/java/org/rajawali3d/materials/plugins/DecalMaterialPlugin.java

addresses #2013, usage:
```
Texture decal = new Texture("decal", R.drawable.decal);
Material material = new Material();
material.addPlugin(new DecalMaterialPlugin(decal));
```
The following texture modifiers are implemented
- Texture.setWrapType()
- Texture.setRepeat()
- Texture.offsetEnabled()
- Texture.setOffset(), setOffsetU(), setOffsetV()

added a Decal material plugin

---

rajawali/src/main/java/org/rajawali3d/animation/Animation.java

in Animation.update(), mElapsedtime could be set larger than mDuration,
causing a value greater than one to be sent to the Interpolator.

addresses issue #1184

---

rajawali/src/main/java/org/rajawali3d/cameras/ArcballCamera.java

addresses #1572 
provides a working override of `ArcballCamera.resetCameraOrientation()`

working implementation of ArcballCamera.resetCameraOrientation()

---

rajawali/src/main/java/org/rajawali3d/Object3D.java

This allow the UV map to be restored on subsequent calls.
adresses #2107

Store original UV map when first calling Object.setAtlasTile()

---

rajawali/src/main/java/org/rajawali3d/materials/Material.java
rajawali/src/main/java/org/rajawali3d/materials/shaders/AShader.java

Modifies Material.createShaders() to make lighting fragments available to custom shaders if necessary.
addresses #2112
now the code becomes
```
DirectionalLight key = new DirectionalLight(-3,4,5);
key.setPower(3.0f);
getCurrentScene().addLight(key);
vertexShader = new VertexShader();
fragmentShader = new DynamicShader();
material = new Material(vertexShader, fragmentShader);
material.setColor(Color.MAGENTA);
material.setColorInfluence(0.5f);
material.setAmbientColor(Color.CYAN);
material.setDiffuseMethod(new DiffuseMethod.Lambert());
material.enableLighting(true);
material.enableTime(true);
Object3D obj = new Cube(2);
obj.setMaterial(material);
getCurrentScene().addChild(obj);
```

implements a simpler approach to lighting Dynamic Materials

---

.circleci/config.yml

It's still broken https://circleci.com/gh/Rajawali/Rajawali/109 as I see https://hub.docker.com/r/rajawali/rajawali/tags
you use now only `1.1` instead with leading _release-_ of previous `release-1.0`
Sorry my fault, I didn't double checked it

fix CircleCI

---

rajawali/src/main/java/org/rajawali3d/Object3D.java

Object3D.getChildByName() now ignores children with no name

---

rajawali/src/main/java/org/rajawali3d/materials/plugins/GreenScreenMaterialPlugin.java

fulfills feature request #2152 
Implements a `PRE_LIGHTING` plugin that divides the texture CrCb color plane into three regions clustered around the keyColor:
- matched texture colors are subtracted from the blend, alpha is set equal to the color influence
- unmatched colors are not changed
- close colors are partially subtracted from the blend, alpha is the key value multiplied by the color influence.

implements a plugin that applies greenscreen (chromakey) efffect to a specified texture

---

rajawali/src/main/java/org/rajawali3d/materials/plugins/VerticalGradientMaterialPlugin.java

overlay color is transparent at the bottom and screened over background at the top.
essentially (1-(1-a*(1-v))*(1-b*v)), where
a is the existing material
b is the overlay
v is the v axis value premultiplied by the overlay opacity

Vertical gradient material plugin

---

rajawali/src/main/java/org/rajawali3d/postprocessing/passes/KaleidoscopePass.java

adresses issue #2159
multiplies the mapping angle to compress the image angularly,
swaps u,v texture axis to maintain vertical symmetry,
allows wraparound to implement the kaleidoscope repetition

Implemented a Kaleidoscope Postprocessing Pass

---

rajawali/src/main/java/org/rajawali3d/materials/Material.java
rajawali/src/main/java/org/rajawali3d/materials/shaders/fragments/texture/LightMapFragmentShaderFragment.java
rajawali/src/main/java/org/rajawali3d/materials/textures/ATexture.java
rajawali/src/main/java/org/rajawali3d/materials/textures/LightMapTexture.java

addresses issue #2163
lightmaps are added after lighting and only to to the rgb channels,
this approach leaves alpha mapping intact.
an example lightmap rendered in blender

implemented basic dynamic light mapping

---

rajawali/src/main/java/org/rajawali3d/materials/plugins/PointApertureMaterialPlugin.java
rajawali/src/main/java/org/rajawali3d/materials/plugins/PointOrbitalMaterialPlugin.java
rajawali/src/main/java/org/rajawali3d/primitives/PointShell.java

implemented `PointShell`, a geometry primitive for point sprite effects
implemented `PointAperatureMaterialPlugin`, a material primitive for point sprite effects
addresses issue #2176
added `PointOrbitalMaterialPlugin`, a simple vertex fragment, animates points by reflecting the initial point position by a plane that rotates through the origin and independently oriented with the initial position of each point. A starting point for highlighting specific objects.
Usage:
```
bgMaterial = new Material();
bgMaterial.enableTime(true);
bgMaterial.useVertexColors(true);
bgMaterial.addPlugin(new PointApertureMaterialPlugin(8));
bgMaterial.addPlugin(new PointOrbitalMaterialPlugin());
Object3D points = new PointShell(1024,2);
points.setTransparent(true);
points.setBlendFunc(GLES20.GL_ONE, …
```

implemented PointShell and PointAperatureMaterialPlugin for point sprite effects

---

rajawali/src/main/java/org/rajawali3d/renderer/Renderer.java

added for use as infrastructure to enable iterating through the scene list.
observed the need while coding a test jig for issue #2179

method to retrieve the number of scenes associated with a renderer

---

rajawali/src/main/java/org/rajawali3d/postprocessing/PostProcessingManager.java

This addresses issue #2181, and might be connected to issue #2179

PostProcessingManager configures non-fullscreen RenderTargets.

---

examples/src/main/java/org/rajawali3d/examples/examples/postprocessing/RenderToTextureFragment.java

This PR fixes two issues that existed on the RenderToTextureFragment example:
1. Crash when backgrounding and then coming back into the app as described in #2179.
2. Removing and re-adding the offscreen texture on every call to `onRender()` was a memory leak of sorts - the example's memory consumption would just grow and grow until the app would crash. In most cases it seemed like it was a GL out of memory crash.
With respect to point 1, the necessary change was to "add" the second scene so that the renderer knew about it.
With respect to point 2, the solution was to just add the offscreen texture to the cube in the init block - it turns out you don't need to re-add it every frame. Doing so once is sufficient for it to render the way one would expect.
Interestingly with this PR the issue …

Fixing a crash and memory issue in RenderToTextureFragment

---

rajawali/src/main/java/org/rajawali3d/materials/Material.java
rajawali/src/main/java/org/rajawali3d/materials/shaders/fragments/texture/DiffuseTextureFragmentShaderFragment.java

by default, CubeMap textures are now diffuse shaded,
and pixel data is assigned using the textureCube mapping system
Sky and Environmental Texture Mappings remain unchanged.
addresses issue #2185

implemented default CubeMap texture loading

---

rajawali/src/main/java/org/rajawali3d/materials/plugins/IndividualMaterialPlugin.java

addresses issue #2187 
IndividualMaterialPlugin(num_points, start, end, lifetime, randomness)
-   num_points: number of vertices in the object
-   start:      time to start activating particles
-   end:        time when all particles are active
-   lifetime:   particle active lifetime
-   randomness: amount of randomness, 0=no ranndomness, 1=fully random

plugin providing individual lifetimes for each particle.

---

.github/workflows/gradle-wrapper-validation.yml

I observed in #2207 this Gradle check job doesn't run
now it does

Check Gradle on each pull request

---

build.gradle
examples/build.gradle
examples/src/main/AndroidManifest.xml
rajawali/build.gradle
vr/build.gradle
vuforia/build.gradle
wear-example/build.gradle
wear/build.gradle

To have a easy-to-use maven, I recommend to use https://jitpack.io
* remove dependency on circleci for proper working version code and name
* change version code and name logic to only depend on git
Now you simply add a tag and you see it here https://jitpack.io/#Rajawali/Rajawali
Ok, current master fails there, but with this pull request it will work. Please see my fork as an example
https://jitpack.io/#hannesa2/rajawali

Jitpack build

---

.github/workflows/Android-CI-release.yml

When you tag a new release, now you will see something similar to this
Ok, almost nobody needs this aar files, but you could add text to release and if someone only watches release and not all other communication
he is triggered on new releases

Release on Github

---

rajawali/src/main/java/org/rajawali3d/primitives/NPrism.java

- Corrects chirilaty of bottom endcap triangles
- Improves endcap UV mapping (slight scaling issue remains)
- Side normals now match that of a Cube
Endcap UVs extend only to a unit circle inscribed within the unit texture.
Not really noticable with anything other than a cubic unit NPrism.
Did not think extra complexity of adressing endcap UV scaling was worth the effort.
addresses issue #2231

Adresses unexpected NPrism behaviour

---

rajawali/src/main/java/org/rajawali3d/primitives/Cube.java
rajawali/src/main/java/org/rajawali3d/primitives/RectangularPrism.java

(also validated Skybox mappings) Updated comments to make the constants a bit more understandable.
addressed #2239

normalizes texture mapping of Cube and RectangularPrism

---

rajawali/src/main/java/org/rajawali3d/materials/plugins/TextureScalingMaterialPlugin.java

to allow scaled primitives to maintain a consistent texture resolution.
addresses part of #2241, currently only works for `Cube` and `RectangularPrism`.

added TextureScalingMaterialPlugin

---

rajawali/src/main/java/org/rajawali3d/primitives/NPrism.java

NPrism testures are now wrapped around the object geometry

---

rajawali/src/main/java/org/rajawali3d/materials/shaders/fragments/diffuse/OrenNayarFragmentShaderFragment.java

forgot to normalize `viewDir` after multiplication

fixed bug in Oren-Nayar diffuse shader

---

rajawali/src/main/java/org/rajawali3d/animation/Animation.java

note that the old `Playable.play()` interface remains unchanged
addresses #2266

implemented reactive animation activation, and direction toggling

---

rajawali/src/main/java/org/rajawali3d/Geometry3D.java

cleaning out an VertexAnimationObject3D dependency that somehow got into Geometry3D

cleaning out an unused VertexAnimationObject3D dependency 

---

rajawali/src/main/java/org/rajawali3d/materials/plugins/PosableMaterialPlugin.java

enabling object geometry transformations from one pose to another.
adresses issue #2275, and improves upon the workaround presented in #1689

added `PosableMaterialPlugin` for geometry transformations

---

rajawali/src/main/java/org/rajawali3d/primitives/Cube.java

corrected comment annotating vertex ordering of the top cube quad, no code change

corrected vertex ordering annotation, no code change

---

rajawali/src/main/java/org/rajawali3d/animation/ExplodingAnimation3D.java
rajawali/src/main/java/org/rajawali3d/materials/plugins/ExplodingMaterialPlugin.java

works like this:
```
@Override
protected void initScene() {
try {
getCurrentScene().setBackgroundColor(Color.CYAN & Color.DKGRAY);
DirectionalLight key = new DirectionalLight(-4,-4,-4);
key.setPower(5/4f);
getCurrentScene().addLight(key);
RectangularPrism prism = new RectangularPrism(2,1,1);
Material material = new Material();
material.setColor(Color.RED | Color.GRAY);
material.setDiffuseMethod(new DiffuseMethod.Lambert());
material.setAmbientColor(Color.CYAN | Color.GRAY);
material.setAmbientIntensity(1/8f,1/8f,1/8f);
material.addPlugin(new ExplodingMaterialPlugin());
material.enableLighting(true);
Object3D obj = new Cube(4);
obj.setScale(1/2f);
obj.setPosition(0,0,0);
obj.setMaterial(material);
obj.setDoubleSided(true);
getCurrentScene().addChild(obj);
Animation3D anim = new …
```

added an animator for the exploding plugin, simplifies rapid disassembly
