Rajawali/Rajawali

- src/rajawali/primitives/RectangularPrism.java
Added a new type of primitive. If it works well, the Cube primitive can be rewrote as a special case of this. Can someone double check the vertices and normals arrays?
> Added Prism primitive.

- src/rajawali/math/Quaternion.java
added function:
public double angleBetween(final Quaternion other)
which returns the angle between the Quaternion and another.
> added angleBetween function

- src/rajawali/ATransformable3D.java
- src/rajawali/Object3D.java
made ATransformable3D.setScale(Vector3 scale) set values of the provided Vector3 to its own instead of creating a pointer to the provided Vector3
> made ATransformable3D.setScale(Vector3 scale) set values instead of creating a pointer

- rajawali/src/main/java/rajawali/math/Quaternion.java
sets the Quaternion to look at a specific coordinate in world space
> added Quaternion.lookAt(Vector3 lookat, Vector3 upDirection)

- rajawali/src/main/java/rajawali/math/Quaternion.java
- rajawali/src/main/java/rajawali/renderer/RajawaliRenderer.java
moved initialization of TextureManager and MaterialManager from
onSurfaceChanged to onSurfaceCreated so Textures and Materials can be
loaded in an override of this method (like google strongly advises in
their developer presentations)
> Manager initialization

- src/rajawali/OrthographicCamera.java
> Thread guards for OrthographicCamera members.

- rajawali/src/main/java/rajawali/math/Quaternion.java
Specify an axis and based on it getXAxis, getYAxis or getZAxis is
returned
> Added getAxis(Axis axis) that returns the specified Axis of the Quaternion

- rajawali/src/main/java/rajawali/curves/ASpiral3D.java
- rajawali/src/main/java/rajawali/curves/ArchimedeanSpiral3D.java
- rajawali/src/main/java/rajawali/curves/LogarithmicSpiral3D.java
- rajawali/src/main/java/rajawali/math/vector/Vector3.java
> Adds Logarithmic and Archimedean spirals.

- rajawali/src/main/java/rajawali/animation/CoalesceAnimation3D.java
- rajawali/src/main/java/rajawali/curves/ASpiral3D.java
- rajawali/src/main/java/rajawali/curves/ArchimedeanSpiral3D.java
- rajawali/src/main/java/rajawali/curves/LogarithmicSpiral3D.java
> Makes a few tweaks to the spiral paths, adds CoalesceAnimation3D.

- .travis.yml
- rajawali/build.gradle
> Updates build.gradle to use version 22 of support libraries.

- rajawali/src/main/java/rajawali/Object3D.java
> Cloned Object3Ds now get names from their origin Object3D fixes #1399

- rajawali/src/main/java/org/rajawali3d/renderer/RajawaliDebugRenderer.java
- rajawali/src/main/java/org/rajawali3d/renderer/RajawaliRenderer.java
- rajawali/src/main/java/org/rajawali3d/util/RajawaliGLDebugger.java
Adds a GL debug enabled renderer and helper class for constructing debug configuration.
> Fixes #1397 Adds GL debug helper

- rajawali/src/main/java/org/rajawali3d/postprocessing/passes/VignettePass.java
- rajawali/src/main/res/raw/vignette_fragment_shader.glsl
Trying to give back... finding this project very useful.
I attempted to implement using the Plugin architecture. But gave up as I found the error messages too difficult. 
Hopefully others will find the Vignette useful.
> Added VignettePass postprocessing effect.

- .idea/inspectionProfiles/Project_Default.xml
- rajawali/src/main/java/org/rajawali3d/Camera.java
- rajawali/src/main/java/org/rajawali3d/primitives/Line3D.java
- rajawali/src/main/java/org/rajawali3d/scene/RajawaliScene.java
- rajawali/src/main/java/org/rajawali3d/util/debugvisualizer/DebugCamera.java
- rajawali/src/main/java/org/rajawali3d/util/debugvisualizer/DebugLight.java
- rajawali/src/main/java/org/rajawali3d/util/debugvisualizer/DebugObject3D.java
- rajawali/src/main/java/org/rajawali3d/util/debugvisualizer/DebugVisualizer.java
- rajawali/src/main/java/org/rajawali3d/util/debugvisualizer/GridFloor.java
Finally added this debug visualizer class. It can be used to draw a grid floor, visualize camera frustums and visualize lights. I will add a trident as well.
Camera frustum visualization was already there but I've removed it out of the scene and camera classes. This is a much cleaner solution.
I will also add an example to the examples app.
> Debug visualizer

- rajawali/src/main/java/org/rajawali3d/scene/ASceneFrameCallback.java
> Fixes bug with ASceneFrameCallback extending AFrameTask.

- rajawali/src/main/java/org/rajawali3d/animation/mesh/SkeletalAnimationChildObject3D.java
- rajawali/src/main/java/org/rajawali3d/animation/mesh/SkeletalAnimationObject3D.java
- rajawali/src/main/java/org/rajawali3d/animation/mesh/SkeletalAnimationSequence.java
- rajawali/src/main/java/org/rajawali3d/loader/LoaderAWD.java
- rajawali/src/main/java/org/rajawali3d/loader/awd/BlockAnimationSet.java
- rajawali/src/main/java/org/rajawali3d/loader/awd/BlockAnimator.java
- rajawali/src/main/java/org/rajawali3d/loader/awd/BlockMeshInstance.java
- rajawali/src/main/java/org/rajawali3d/loader/awd/BlockSimpleMaterial.java
- rajawali/src/main/java/org/rajawali3d/loader/awd/BlockSkeleton.java
- rajawali/src/main/java/org/rajawali3d/loader/awd/BlockSkeletonAnimation.java
- rajawali/src/main/java/org/rajawali3d/loader/awd/BlockSkeletonPose.java
- rajawali/src/main/java/org/rajawali3d/loader/awd/BlockTriangleGeometry.java
- rajawali/src/main/java/org/rajawali3d/math/Matrix4.java
- rajawali/src/main/java/org/rajawali3d/util/LittleEndianDataInputStream.java
Adds AWD skeletal animation parsing, along with a couple of fixes. Developed using an AWD version of the boblampclean MD5 model and a few other simple test models. There is some relatively minor but noticeable distortion of the models during animation, but unfortunately I won't have time in the near future to pin this down.
> AWD skeletal animation parsing

- rajawali/build.gradle
- rajawali/src/main/java/org/rajawali3d/renderer/RajawaliPipRenderer.java
- rajawali/src/main/java/org/rajawali3d/renderer/pip/SubRenderer.java
- rajawali/src/main/java/org/rajawali3d/renderer/pip/WorkaroundScreenQuad.java
This is a proposed contribution based on the [RajawaliSideBySideRenderer](https://github.com/Rajawali/Rajawali/blob/master/rajawali/src/main/java/org/rajawali3d/renderer/RajawaliSideBySideRenderer.java) which allows rendering two separate scenes in the same view / GLES thread.
[Here you can find](https://github.com/creativa77/RajawaliExamplePip) a very simple example use of this contribution.
Looking forward to comments and suggestions for improvement.
> "Picture-in-picture" renderer contribution

- .travis.yml
- build.gradle
- rajawali/build.gradle
Update target and compile sdk to 23.
Fix Travis config.
Had to add legacy alias because of this : http://stackoverflow.com/questions/31433687/android-gradle-apache-httpclient-does-not-exist
> Update Gradle plugin and compile SDK version

- rajawali/src/main/java/org/rajawali3d/primitives/Cylinder.java
- rajawali/src/main/java/org/rajawali3d/primitives/Torus.java
based on the code for the Sphere primitive.
> Cylinder and Torus primitives

- rajawali/src/main/java/org/rajawali3d/primitives/ScreenQuad.java
So we can use custom vertex shaders effects.
This is my first pull request, please let me know if I have not followed any of the normal process.
> Added segmentation to screen quads.

- .gitignore
- rajawali/src/main/java/org/rajawali3d/scene/Scene.java
Took a couple of tries for me to figure out how to get the remove to happen...
> Lib vuforia build fix

- rajawali/src/main/java/org/rajawali3d/Object3D.java
Documentation only
Any feedback is welcome: accuracy, vocabulary, style, completeness, verbosity; praise, condemnation, laughter...
> PR Fixing #1550 - Object3D.setScreenCoordinates() anomaly?

- rajawali/src/main/java/org/rajawali3d/math/Quaternion.java
- rajawali/src/main/java/org/rajawali3d/math/vector/Vector3.java
> Fixes #1616.

- examples/src/main/java/org/rajawali3d/examples/ExamplesActivity.java
- examples/src/main/java/org/rajawali3d/examples/ExamplesApplication.java
- examples/src/main/java/org/rajawali3d/examples/examples/about/MeetTheTeamFragment.java
- examples/src/main/java/org/rajawali3d/examples/views/GithubLogoView.java
Master already contains partial resolutions for this issue. These two commits resolve the outstanding broken linking issues.
> 1579 examples update

- examples/src/main/java/org/rajawali3d/examples/ExamplesFragment.java
- examples/src/main/java/org/rajawali3d/examples/recycler/CategoryAdapter.java
- examples/src/main/res/menu/menu_search.xml
- examples/src/main/res/values/strings.xml
- Search is based on String.contains() and lower case input and names.
- Category name matches include all tests in the category
- Zero length search results in all items returned
- Single example result is opened when action done is selected
> #1627 Implemented a simple search

- examples/src/main/AndroidManifest.xml
- examples/src/main/res/values/strings.xml
- examples/src/withVuforia/AndroidManifest.xml
- Moved the vuforia specific activity to the variant manifest letting the plugin perform merge
- Updated the activity names so they can be differentiated.
> #1638 Split vuforia activity to variant manifest

- examples/build.gradle
- examples/src/main/AndroidManifest.xml
- wear-example/build.gradle
- wear-example/src/main/AndroidManifest.xml
- wear-example/src/main/java/org/rajawali3d/examples/wear/WatchService.java
Wear appears to work, haven't tested the main apk install but it should be good.
> 1636 add wear to examples

- examples/src/main/java/org/rajawali3d/examples/examples/general/DebugVisualizerFragment.java
- rajawali/src/main/java/org/rajawali3d/debug/CoordinateTrident.java
Fixes #1513. Task #1436. Adds coordinate axis trident. It can be scaled/positioned like any other object.
> Coordinate axis debug trident.

- build.gradle
- examples/build.gradle
- rajawali/build.gradle
- versions.gradle
- vr/build.gradle
- vuforia/build.gradle
- wear-example/build.gradle
- wear/build.gradle
Moved all build versions to the versions.gradle script. Left deps alone as I feel like they are probably fine in their own file.
> #1637 Consolidated all build related versions to single gradle script

- rajawali/src/main/java/org/rajawali3d/view/SurfaceView.java
- rajawali/src/main/java/org/rajawali3d/view/TextureView.java
Fixes #1696 
@MasDennis could you please review?
> Fix design view in Android Studio

- rajawali/src/main/java/org/rajawali3d/scene/Scene.java
Add updateSkybox(Bitmap[] bitmaps) so that users can update skybox at the runtime, for example, with images downloaded from internet.
> add accepting bitmap array for updateSkybox

- rajawali/src/main/java/org/rajawali3d/math/Matrix4.java
There were some inconsistency in calculating the inverse of w used for perspective division after multiplying the vector and the matrix. 
The same for projectAndCreateVector method aswell
> fixed inconsistency in obtaining 1/w

- rajawali/src/main/java/org/rajawali3d/animation/RotateAnimation3D.java
- rajawali/src/main/java/org/rajawali3d/math/Quaternion.java
fix for  #1319, RotateAnimation3D more than 180 degrees, sorry I put "obtuse" in the commit comments when I meant reflex angles.
> RotateAnimation3D now goes the long way around for reflex angles

- rajawali/lint.xml
- rajawali/src/main/java/org/rajawali3d/materials/textures/Etc2Texture.java
- rajawali/src/main/java/org/rajawali3d/postprocessing/passes/FXAAPass.java
- rajawali/src/main/java/org/rajawali3d/util/Capabilities.java
- rajawali/src/main/java/org/rajawali3d/util/egl/RajawaliEGLConfigChooser.java
- rajawali/src/main/java/org/rajawali3d/view/TextureView.java
Corrects inlined API lint issues and reduces click accessibility issue to informational only
> Fixes #1589

- rajawali/src/main/java/org/rajawali3d/util/Capabilities.java
> Fixes #1743

- build.gradle
Signed-off-by: Jared Woolston <Jared.Woolston@gmail.com>
> Updates build tools.

- rajawali/src/main/java/org/rajawali3d/renderer/Renderer.java
Signed-off-by: Jared Woolston <Jared.Woolston@gmail.com>
> Updates version number for release.

- .travis.yml
Signed-off-by: Jared Woolston <Jared.Woolston@gmail.com>
> Adds slack notification to travis config.

- rajawali/src/main/java/org/rajawali3d/postprocessing/passes/ScanlinePass.java
- rajawali/src/main/res/raw/scanline_fragment_shader.glsl
Trying to give back... finding this project very useful.
Screenshot from:
```
mEffects = new PostProcessingManager(this);
RenderPass renderPass = new RenderPass(getCurrentScene(), getCurrentCamera(), 0);
mEffects.addPass(renderPass);
EffectPass scanlinePass = new ScanlinePass(0.75f,4,mCurrentViewportWidth, mCurrentViewportHeight);
scanlinePass.setRenderToScreen(true);
mEffects.addPass(scanlinePass);
```
> Added ScanlinePass postprocessing effect.

- rajawali/src/main/java/org/rajawali3d/Geometry3D.java
Signed-off-by: Jared Woolston <Jared.Woolston@gmail.com>
> FIxes #1810

- rajawali/src/main/java/org/rajawali3d/renderer/Renderer.java
> Updates build number for new release.

- .travis.yml
- build.gradle
- rajawali/build.gradle
- Storage is configured with .aws credentials and is setup to be configured by travis
- .travis.yml is not updated to run upload task and will require additional modification
> Added support to publish test results to AWS S3 storage

- README.md
This is not #1836, just something else I came across looking into it.
> fixed link to plugin tutorial

- rajawali/build.gradle
as well as for unit tests run on connected devices
(so we can just rename the androidTest directory to run unit tests locally)
> allowed junit to be compiled for local unit tests

- rajawali/src/main/java/org/rajawali3d/materials/shaders/AShader.java
an alternative fix for issue #1885
> another approach to not building a shaderstring when a shaderstring is provided

- rajawali/src/main/java/org/rajawali3d/materials/methods/DiffuseMethod.java
> Toon shader is now setting colors as expected.

- rajawali/src/main/java/org/rajawali3d/materials/shaders/fragments/texture/EnvironmentMapFragmentShaderFragment.java
addresses Unexpected Spherical Environment Mapping #1916
> now normalizing reflected V_EYE_DIR after setting Z component.

- rajawali/src/androidTest/java/org/rajawali3d/math/Matrix4Test.java
verifies that given an invertable matrix:
- a matrix times it's inverse equals the identity matrix
- an inverse times it's matrix equals the identity matrix
> added more inverse matrix unit tests

- rajawali/src/androidTest/java/org/rajawali3d/materials/shaders/AShaderTest.java
- rajawali/src/main/java/org/rajawali3d/materials/shaders/AShaderBase.java
addresses issue #1923 which also cropped up in #1922
> corrected Vec2, Vec3 and Vec4 assignments

- rajawali/src/androidTest/java/org/rajawali3d/math/QuaternionTest.java
added Quaternion commutativity, associativity, and distributivity unit tests
added a division unit test commented out because it (unexpectedly) fails, see #1897
> additional Quaternion unit tests

- rajawali/src/main/java/org/rajawali3d/Object3D.java
- rajawali/src/main/java/org/rajawali3d/materials/Material.java
- rajawali/src/main/java/org/rajawali3d/materials/shaders/AShaderBase.java
- rajawali/src/main/java/org/rajawali3d/materials/shaders/FragmentShader.java
- rajawali/src/main/java/org/rajawali3d/materials/shaders/VertexShader.java
- rajawali/src/main/java/org/rajawali3d/materials/shaders/fragments/texture/EnvironmentMapFragmentShaderFragment.java
made the InverseViewMatrix available to the Environmental Mapping Shader,
(as the inverse function is not yet available in GLSL ES)
and updated the Environmental shader fragment to update mapping with the camera position.
Not 100% perfect, not yet handling camera rotations about the Z axis, but addresses most of #1920
> Improved Environmental Cube Mapping

- rajawali/src/androidTest/java/org/rajawali3d/curves/LinearBezierTest.java
- rajawali/src/androidTest/java/org/rajawali3d/curves/QuadraticBezierTest.java
- rajawali/src/main/java/org/rajawali3d/curves/QuadraticBezierCurve3D.java
added unit tests and corrected initialisation of `QuadraticBezierCurve3D` `tmpPoint[123]` variables.
resolves issue #1926
> Quadratic Bezier Fix

- rajawali/src/androidTest/java/org/rajawali3d/curves/QuadraticBezierTest.java
- rajawali/src/main/java/org/rajawali3d/curves/QuadraticBezierCurve3D.java
addresses issue #1928 
for Camden Hells, we can drop `QuadraticBezierCurve3D.setCalculateTangents()` and just get a tangent with `QuadraticBezierCurve3D.getTangent(double t)`
> fixed tangent calculations

- rajawali/src/main/java/org/rajawali3d/curves/QuadraticBezierCurve3D.java
> reducing clones() in getCurrentTangent()

- rajawali/src/androidTest/java/org/rajawali3d/curves/CubicBezierTest.java
- rajawali/src/main/java/org/rajawali3d/curves/CubicBezierCurve3D.java
- rajawali/src/main/java/org/rajawali3d/curves/QuadraticBezierCurve3D.java
similar to the Quadratic Bezier fix
extension to #1928
> Cubic Bezier fix

- rajawali/src/androidTest/java/org/rajawali3d/util/IntersectorTest.java
- rajawali/src/main/java/org/rajawali3d/util/Intersector.java
addresses Unexpected Intersector.intersectRaySphere() behavior #1932
> now correctly setting and scaling hitPoint

- rajawali/src/androidTest/java/org/rajawali3d/util/IntersectorTest.java
> corrected package name

- rajawali/src/androidTest/java/org/rajawali3d/Geometry3Dtest.java
- rajawali/src/androidTest/java/org/rajawali3d/bounds/BoundingSphereTest.java
might be needed if something show up in #1925
> added unit tests for Geometry3D and BoundingSphere

- rajawali/src/main/java/org/rajawali3d/Object3D.java
- rajawali/src/main/java/org/rajawali3d/materials/shaders/fragments/texture/EnvironmentMapFragmentShaderFragment.java
forgot to transpose the reflection matrix in my last checkin
resolves the rest of #1920
> fixed camera Z axis rotation issue

- rajawali/src/main/java/org/rajawali3d/terrain/TerrainGenerator.java
> Terrain Normals now match the direction of normals of other primitives

- rajawali/src/androidTest/java/org/rajawali3d/math/QuaternionTest.java
- rajawali/src/main/java/org/rajawali3d/math/Quaternion.java
fix for Quaternion.pow works only for unit Quaternions #1899
> Quaternion.pow now works for non-unit quaternions

- rajawali/src/main/java/org/rajawali3d/materials/shaders/fragments/texture/DiffuseTextureFragmentShaderFragment.java
> added support of mixed (Image and Video) texture mapping.

- build.gradle
- dev/camdenhells/REQUIREMENTS.md
(and design stub)
Hey all,
In preparing for a relatively large/complex WIP PR for the v2.0-core-dev branch, I realized that I have been evolving a fairly large set of related but implicit requirements in my mind, and that submitting my code without first enumerating those requirements would needlessly complicate discussion by mixing non-trivial requirements, design, and code issues all at the same time.
So I decided to document what I had been thinking, which of course forced me to get concrete.  Which in turn forced me to consider the entire range of requirements, and - as best I could - to review and incorporate as many of the relevant Camden Hells Milestone issues and various other discussions. There still may well be some gaping holes.
I hope this PR stimulates lots of fresh …
> Initial submission of formal Camden Hells requirements document

- rajawali/src/main/java/org/rajawali3d/scene/Scene.java
addresses issues raised in #1904
also partially cleans up skybox implementation
> added ability to set skybox geometry

- rajawali/build.gradle
- rajawali/src/androidTest/java/org/rajawali3d/primities/ScreenQuadTest.java
- rajawali/src/main/java/org/rajawali3d/postprocessing/PostProcessingManager.java
- rajawali/src/main/java/org/rajawali3d/primitives/ScreenQuad.java
ScreenQuad texture mapping Fix for #1980
> ScreenQuad now handles CW and CCW texture mapping

- rajawali/src/androidTest/java/org/rajawali3d/visitors/RayPickingVisitorTest.java
- rajawali/src/main/java/org/rajawali3d/renderer/Renderer.java
- rajawali/src/main/java/org/rajawali3d/util/RayPicker.java
- rajawali/src/main/java/org/rajawali3d/visitors/RayPickingVisitor.java
addresses issues arising in #2007 
the following now behaves as expected:
```
public class RayPickerRenderer extends Renderer {
private DirectionalLight directionalLight;
private RayPicker picker;
public RayPickerRenderer(Context context) {
super(context);
}
@Override
protected void initScene() {
getCurrentScene().setBackgroundColor(Color.BLUE);
directionalLight = new DirectionalLight(1.0, 0.2, 1.0);
directionalLight.setPower(1.0f);
getCurrentScene().addLight(directionalLight);
Random r = new Random();
for(int i=0; i<28; i++){
Material material = new Material();
material.setColor(Color.CYAN);
material.setDiffuseMethod(new DiffuseMethod.Lambert());
material.enableLighting(true);
Vector3 position = new Vector3(r.nextFloat(), r.nextFloat(), r.nextFloat());
position.multiply(6);
Cube child = …
```
> Ray picker now implements a bounding sphere intersection test

- rajawali/src/androidTest/java/org/rajawali3d/ATransformable3DTest.java
- rajawali/src/main/java/org/rajawali3d/ATransformable3D.java
Confirms behavior described in #2003 and demonstrates unexpected setRotX/getRotX and setRotZ/getRotZ behaviors.
> first pass unit tests for ATransformable3D

- rajawali/src/main/java/org/rajawali3d/postprocessing/effects/OutlineEffect.java
- rajawali/src/main/java/org/rajawali3d/postprocessing/passes/BlendPass.java
- rajawali/src/main/java/org/rajawali3d/postprocessing/passes/SobelPass.java
- rajawali/src/main/res/raw/blend_subtract_fragment_shader
Implemented a Sobel postprocessing filter, added a subtract mode to BlendPass,
combined it all to create a simple OutlineEffect.
> Adding realtime non-photorealisting rendering (NPR) to Rajawali.

- rajawali/src/main/java/org/rajawali3d/animation/SplineTranslateAnimation3D.java
> added optional Look At target for spline translation animations.

- .travis.yml
- rajawali/src/androidTest/java/org/rajawali3d/ATransformable3DTest.java
- rajawali/src/androidTest/java/org/rajawali3d/Geometry3Dtest.java
- rajawali/src/androidTest/java/org/rajawali3d/WorldParametersTest.java
- rajawali/src/androidTest/java/org/rajawali3d/animation/SlerpAnimation3Dtest.java
- rajawali/src/androidTest/java/org/rajawali3d/bounds/BoundingSphereTest.java
- rajawali/src/androidTest/java/org/rajawali3d/cameras/FrustumTest.java
- rajawali/src/androidTest/java/org/rajawali3d/curves/CubicBezierTest.java
- rajawali/src/androidTest/java/org/rajawali3d/curves/LinearBezierTest.java
- rajawali/src/androidTest/java/org/rajawali3d/curves/QuadraticBezierTest.java
- rajawali/src/androidTest/java/org/rajawali3d/materials/shaders/AShaderTest.java
- rajawali/src/androidTest/java/org/rajawali3d/math/Matrix4Test.java
- rajawali/src/androidTest/java/org/rajawali3d/math/QuaternionTest.java
- rajawali/src/androidTest/java/org/rajawali3d/math/vector/Vector3Test.java
- rajawali/src/androidTest/java/org/rajawali3d/primities/ScreenQuadTest.java
- rajawali/src/androidTest/java/org/rajawali3d/util/ArrayUtilsTest.java
- rajawali/src/androidTest/java/org/rajawali3d/util/IntersectorTest.java
- rajawali/src/androidTest/java/org/rajawali3d/visitors/RayPickingVisitorTest.java
> make tests build

- .travis.yml
- .travis/install-ndk.sh
I removed all non working stuff from Travis to make it green
> Fix Travis for pull requests

- rajawali/src/main/java/org/rajawali3d/materials/textures/TexturePacker.java
resetting InputStreams before extracting image data.
> addresses #2097

- examples/src/main/java/org/rajawali3d/examples/data/DataSet.java
- examples/src/main/res/values/data_items.xml
> Use Accelerometer Example

- rajawali/src/main/java/org/rajawali3d/util/egl/RajawaliEGLConfigChooser.kt
- rajawali/src/main/java/org/rajawali3d/view/IRajawaliEglConfigChooser.kt
- rajawali/src/main/java/org/rajawali3d/view/TextureView.kt
Emulator crashes with `ISurface.ANTI_ALIASING_CONFIG.MULTISAMPLING` and this PR is a suggestion how to handle with this:
A Toast instead of a crash.
It's related to https://github.com/Rajawali/Rajawali/issues/2091
> Toast instead of crash

- .circleci/config.yml
This is a test drive if my [change](https://github.com/Rajawali/RajawaliDocker/pull/2) fix the CI [issue](https://circleci.com/gh/Rajawali/Rajawali/108?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack).
As soon as a new tag exists here https://hub.docker.com/r/rajawali/rajawali/tags I can move to this
> attempt to fix CircleCI

- rajawali/src/main/java/org/rajawali3d/postprocessing/passes/RadialBlurPass.java
addresses issue  #2155
because realtime volumetric effects are too costly for phones
> added RadialBlurPass postprocessing effect

- rajawali/src/main/java/org/rajawali3d/materials/shaders/AShader.java
> implemented stringifiers for the GLSL abs function

- rajawali/src/main/java/org/rajawali3d/materials/shaders/AShader.java
- rajawali/src/main/java/org/rajawali3d/materials/shaders/IShaderFragment.java
> Implemented a basic function declaration and definition mechanism.

- rajawali/src/main/java/org/rajawali3d/materials/plugins/VerticalGradientMaterialPlugin.java
sorry, somehow missed this one...
> missed the GLES20 import in VerticalGradientMaterialPlugin

- rajawali/src/main/java/org/rajawali3d/materials/plugins/FresnelMaterialPlugin.java
The fresnel equations are a versatile effect for improving the look of solids.
addresses issue #2169
> Implements a simplified approximation of the Fresnel Equation

- examples/src/main/java/org/rajawali3d/examples/examples/interactive/points/PointSpriteSuperNova.java
could be simplified with the addition of a few point sprite specific features in main library.
addresses issue #2172
> functional point sprite example

- rajawali/src/main/java/org/rajawali3d/materials/shaders/AShader.java
- rajawali/src/main/java/org/rajawali3d/materials/shaders/AShaderBase.java
implemented stringifiers for GLES 2.0 functions gl_PointCoord and gl_PointSize
addresses issue #2174
> stringifiers for GLES 2.0 functions gl_PointCoord and gl_PointSize

- rajawali/src/main/java/org/rajawali3d/view/TextureView.kt
fixed "Type mismatch: inferred type is String? but String was expected" warnings
> addressed Kotlin warnings

- rajawali/src/main/java/org/rajawali3d/materials/shaders/AShader.java
- rajawali/src/main/java/org/rajawali3d/postprocessing/passes/TilePass.java
addresses issue #2204 
accepts rows and columns values greater than one, will stretch if rows != columns
> adds tiling postprocessing effect

- examples/src/main/AndroidManifest.xml
- examples/src/main/java/org/rajawali3d/examples/LauncherActivity.java
> No phone permission

- .github/workflows/Android-CI-Espresso.yml
Simplify CI and parallelize it fro faster run
> Simplify CI

- .github/workflows/Android-CI-Espresso.yml
- .gitignore
- build.gradle
- examples/build.gradle
- examples/src/androidTest/java/org/rajawali3d/examples/LauncherSmokeTest.kt
- examples/src/debug/AndroidManifest.xml
- examples/src/main/java/org/rajawali3d/examples/LauncherActivity.java
- rajawali/build.gradle
- wear/build.gradle
Currently there is only one[ pointless Espresso test](https://github.com/Rajawali/Rajawali/blob/master/rajawali/src/androidTest/java/org/rajawali3d/renderer/RendererTest.java) which tests nothing.
This pull request tests only if build apk is able to start without a crash and additionally makes a screenshot and uploads it to CI job
This **Rajawali-Espresso** Zip contains
* logcat output
* Espresso test html result
* Screenshot of test
Give it a try and look into it !
> Smoke test with screenshot

- rajawali/src/main/java/org/rajawali3d/renderer/Renderer.java
Using a hard coded version is very error prone
> Version logging

- rajawali/src/main/java/org/rajawali3d/cameras/ArcballCamera.java
- rajawali/src/main/java/org/rajawali3d/debug/NormalsObject3D.java
- rajawali/src/main/java/org/rajawali3d/loader/Loader3DSMax.java
- rajawali/src/main/java/org/rajawali3d/loader/LoaderOBJ.java
- rajawali/src/main/java/org/rajawali3d/loader/fbx/FBXValues.java
- rajawali/src/main/java/org/rajawali3d/loader/fbx/LoaderFBX.java
@ValkA looks like has lost interest of https://github.com/Rajawali/Rajawali/pull/2134 
That's why I rebased it to recent master and removed requested build changes
> Fbx import

- rajawali/src/test/java/org/rajawali3d/ATransformable3DTest.java
- rajawali/src/test/java/org/rajawali3d/Transformable3D.kt
I extracted inner class too, otherwise I got the Lint warning to be static
> Fix lowercase class name

- examples/src/main/java/org/rajawali3d/examples/examples/interactive/ObjectPickingFragment.java
I'm investigation the rotation behavior, but it confuses me.
To do so, I let 
* monkey1 rotate on X axis 
* monkey4 rotate on Z axis
* monkey2 and monkey3 keep rotate on Y axis 👍 
But monkey1 and monkey4 are stop rotating !
I've no clue what's wrong here. Maybe you see my error, or the error in Rajawali itself.
This is one of two issues I observe in rotate something with Rajawali (Of course, I will create the second too)
This pull request is more a demonstration of an error. If it's not merged, I'm fine too
> Rotation rotation change

- examples/build.gradle
- examples/src/main/java/org/rajawali3d/examples/data/DataSet.java
- examples/src/main/java/org/rajawali3d/examples/examples/interactive/ObjectRotateFragment.kt
- examples/src/main/java/org/rajawali3d/examples/utils/DoubleUtils.kt
- examples/src/main/res/layout/object_roate_overlay.xml
- examples/src/main/res/values/data_items.xml
I'm investigation the rotation behavior, but it confuses me.
That's why I made an example, but something is confusing here !
Change Z axis need a `monkey.rotX = value`
dataRenderer?.rotateDataX(progress.toDouble())
textMixed.text = "Z=${progress}"
Change X axis need a `monkey.rotZ = value`
dataRenderer?.rotateDataZ(progress.toDouble())
textHorizontal.text = "X=${progress}"
Something is here not right, beginning with my XYZ rotation image, the sample or Rajawali library
This is one of two issues I observe in rotate something with Rajawali
> Rotate example

- build.gradle
- vuforia/build.gradle
- wear/build.gradle
> Remove Lint warnings in build

- rajawali/src/main/java/org/rajawali3d/primitives/Sphere.java
Pathological cases now nolonger attempt to construct geometry.
Adresses issue #2229
> Added corner case handling for Sphere constructors

- .github/dependabot.yml
- build.gradle
- examples/build.gradle
I enabled [dependabot](https://dependabot.com/docs/config-file/), that's why I got them.
> Update libs with dependa bot

- rajawali/src/main/java/org/rajawali3d/materials/plugins/NormalColorMaterialPlugin.java
- rajawali/src/main/java/org/rajawali3d/materials/plugins/PositionColorMaterialPlugin.java
`NormalColorMaterialPlugin` and `PositionColorMaterialPlugin`
addresses issue #2250
> added false color instrumentation plugins

- rajawali/src/main/java/org/rajawali3d/materials/shaders/fragments/specular/PhongFragmentShaderFragment.java
Now calculating Phong highlight position using the half angle between the view direction and the light direction.
Addresses issue #2255
> Improved Phong highlight position

- rajawali/src/main/java/org/rajawali3d/materials/methods/SpecularMethod.java
- rajawali/src/main/java/org/rajawali3d/materials/shaders/fragments/specular/CookTorranceFragmentShaderFragment.java
added a microfacet Cook-Torrance specular reflectance method, surfaces look more metallic and less plastic.
addresses #2257
> Cook Torrance (Microfacet) Specular reflectance Method

- rajawali/src/main/java/org/rajawali3d/loader/LoaderOBJ.java
so `RotateOnAxisAnimation` and `ScaleAnimation3D` work on child objects as expected
addresses #2262
> added an optional parent/child offset capability to LoaderObj.parse()

- rajawali/src/main/java/org/rajawali3d/animation/SplineScalingAnimation3D.java
organically interpolating object scaling between each keyframe
addresses issue #2268
> implemented SplineScalingAnimation3D 

- rajawali/src/main/java/org/rajawali3d/animation/SplineOrientationAnimation3D.java
- rajawali/src/main/java/org/rajawali3d/curves/ICurve4D.java
- rajawali/src/main/java/org/rajawali3d/curves/Path3D.java
- rajawali/src/main/java/org/rajawali3d/curves/Path4D.java
addresses issue #2270
also adds an implementation of 3D and 4D linear paths to support spline animators
> added a spline orientation animator

- rajawali/src/main/java/org/rajawali3d/animation/PosableAnimation3D.java
- rajawali/src/main/java/org/rajawali3d/materials/plugins/PosableMaterialPlugin.java
simplifies animating deforms:
```
@Override
protected void initScene() {
try {
float[] vertices = {
3, 2, 2, 		-1, 2, 2,     -3, -2, 2,		1, -2, 2, // 0-1-2-3 front
3, 2, -2,		 3, 2, 2,      1, -2, 2,		 1, -2, -2, // 5-0-3-4 right
-1, 2, -2,		3, 2, -2,      1, -2, -2, 		-3, -2, -2, // 6-5-4-7 back
-1, 2, 2,		-1, 2, -2,    -3, -2, -2,		-3,-2, 2, // 1-6-7-2 left
-1, 2, 2,		 3, 2, 2,      3, 2, -2,		-1, 2, -2,  // 1-0-5-6 top
1, -2, 2,		-3, -2, 2,    -3, -2, -2,		1, -2, -2, // 3-2-7-4 bottom
};
float[] normals = {
0, 0, 1,    0, 0, 1,    0, 0, 1,    0, 0, 1, // front
0.8944f, 0, -0.4472f,    0.8944f, 0, -0.4472f,    0.8944f, 0, -0.4472f,    0.8944f, 0, -0.4472f, // right
0, 0, -1,   0, 0, -1,   0, 0, -1,   0, 0, -1, // back
-0.8944f, 0, 0.4472f,    -0.8944f, 0, 0.4472f,    -0.8944f, 0, …
```
> added an animator for the PosableMaterialPlugin

- README.md
- rajawali/src/main/java/org/rajawali3d/primitives/Cube.java
better late than never... an attempt at a quick summary, please adjust as needed.
sorry the comment change got in here too, but it is only a comment change so it didn't seem worth redoing the pull request.
> Release news

- rajawali/src/main/java/org/rajawali3d/materials/plugins/PivotPointMaterialPlugin.java
allows a user to alter the origin (pivot point) of an object.
addresses issue #2282 and probably  #2261 #1528 #1469 #1331 #1099
> added a PivotPointMaterialPlugin that offsets geometry vertices

- build.gradle
- publish.gradle
Fixes snapshot builds and ups the version to 1.3
> Adding back support for snapshots

- README.md
> Readme warning
